### ISSUE TITLE
Outdated doc item

### ISSUE THREAD

**Issue by hizir-bc** [BroadcomMFD/test4z#88]
https://github.com/BroadcomMFD/test4z/blob/main/samples/README.md#notes

item 2 needs to be removed as we support it since v2.0.0

**Comment by hizir-bc** [comment]
Copy feature generates a temporary data set when it runs. We recommend you to delete the temporary data set by opening the terminal and issuing the following command:

 npx zowe zos-files delete data-set 'HLQ.TEST4Z.BATCHAPP.DATA(CUSTINC)' -f

Click [here](https://docs.zowe.org/stable/web_help/docs/zowe_zos-files_delete_data-set.html) for more information about the ZOWE data set delete command.



-----
this entire section

**Comment by vahidbaharvand** [comment]
Removed
