### ISSUE TITLE
The setZomsf script and setTest4z scripts

### ISSUE THREAD

**Issue by McQuitty-Broadcom** [BroadcomMFD/test4z#94]
The scripts should be cleaned up to be consistent.
In .scripts/set_test4z.py the prompt is for the URL:
host = input("Host Url (starts with https:// or http://): ")
First, the url could be with the port number but the user doesn't realize this until you get to the next step.

In .scripts/set_zosmf.py, you prompt for the URL, but the code expects HOST:PORT.

I would suggest prompting for the values of all items needed.

For example, in set_test4z.py, it could be refactored to:
print("\nPlease enter Test4z specific information when the command prompt asks")
protocol = input("HTTP or HTTPS")
host = input("Hostname or IP Address: ")
config.set('TEST4Z','host_url', protocol + "://" + host)
port = input("Port: ")
config.set('TEST4Z','port', port)
hlq = input("HLQ: ")
config.set('TEST4Z','hlq', hlq)
user_name = input("Username: ")
config.set('TEST4Z','user', user_name)
password = input("Password: ")
config.set('TEST4Z','password', password)

And set_zosmf.py:
print("\nPlease enter Z/OSMF specific information when the command prompt asks")
host = input("Hostname or IP) : ")
port = input("Port: ")
config.set('ZOSMF','host_url', host + ":" + port)
user_name = input("Username: ")
config.set('ZOSMF','user', user_name)
password = input("Password: ")
config.set('ZOSMF','password', password)

It would be far more consistent, and we know it is https for ZOSMF, so we don't prompt.

**Comment by hizir-bc** [comment]
Hello Tom, 

Thanks for your inputs. Today in the standup, we had a discussion with the team, and we decided to stick with as it is for now.


```
CXXXXXXXXXX:test4z hizircaginbektas$ cd samples/python/
CXXXXXXXXXX:python hizircaginbektas$ cd src/main/.scripts/ && python set_zosmf.py && cd ../../..

Please enter Z/OSMF specific information when the command prompt asks
Protocol: https (default - cannot be edited)
Host Url: lpar1.hostname.com
Port: 1234
Username: USER1
Password: ******

Z/OSMF information collected successfully
CXXXXXXXXXX:python hizircaginbektas$ cd src/main/.scripts/ && python set_test4z.py && cd ../../..

Please enter Test4z specific information when the command prompt asks
Protocol: https (default)
Host Url: lpar1.hostname.com
Port: 2345
HLQ: USER1.T4Z
Username: USER1
Password: ***** 

Test4z information collected successfully
```
