### ISSUE TITLE
Python sample readme contains misleading installation instructions for pytest

### ISSUE THREAD

**Issue by ogonch** [BroadcomMFD/test4z#98]
https://github.com/BroadcomMFD/test4z/blob/main/samples/python/README.md contains this:

> For Windows users, make sure to have the path variable for Pytest in the system settings. Try the following command to check:

> pytest --version
> If the command is not recognised, follow [this](https://www.educative.io/edpresso/how-to-add-python-to-path-variable-in-windows) url to see the guide.

Actual: URL leads to the path variable guide.

Expected: URL should lead to the pytest installation guide.

**Comment by hizir-bc** [comment]
https://github.com/BroadcomMFD/test4z/pull/99

**Comment by hizir-bc** [comment]
Resolved with https://github.com/BroadcomMFD/test4z/pull/99
